[day4]
kakao-ent-2022/w2-signup-profile pull request #11
Opened 2022-01-20 04:47 UTC by lauren-c-kakaoent

- regex 이용하여 id, password 체크

2022-01-20 05:45 UTC, kyoo-sl commented on KakaoProfile/KakaoProfile/SignUpViewController.swift
> +        if !User.isValidPassword(password: password, patterns: [.LENGTH]) {
아래 스샷처럼 8자-16자 사이로 입력했는데, 안내문구가 잘못 된것 같아요~ 아니면 정상적인 스펙인가요?
가능한 여러 케이스로 테스트해보면 좋을 것 같아요!

<image src="https://user-images.githubusercontent.com/97584466/150280529-6abac538-5035-41a9-b530-08c97bfb1e0d.png" width="25%">

2022-01-20 05:47 UTC, kyoo-sl commented on KakaoProfile/KakaoProfile/signup/SignUpViewController.swift
> +    @IBOutlet var nameAlertLabel: UILabel!
nameAlertLabel는 하단에서 사용하지 않는데, 누락된 스펙이 있는 걸까요?
아니라면 불필요하니 삭제하면 좋을 것 같아요~

2022-01-20 06:06 UTC, kyoo-sl commented on KakaoProfile/KakaoProfile/signup/SignUpViewController.swift
> +    @IBAction func idInputDidEnd(_ sender: SignUpTextField) {
@lauren-c-kakaoent  네가지 종류의 TextField에 각각 DidEnd & DidChanged을 @IBAction으로 만들었는데요.
혹시 DidEnd와 DidChanged 두가지만 만들고, 내부에서 종류에 따라 처리할 수 있는 방법은 없을까요??
(이건 반영하지 않을셔도 되고요~ 중복을 줄일 수 있는 방법이 잇는지 궁금해서요!)

2022-01-20 09:42 UTC, bamiboo requested changes

2022-01-20 09:42 UTC, bamiboo commented on KakaoProfile/KakaoProfile/signup/SignUpTextField.swift
> +    }
alert/basic 둘중 하나의 타입만 적용되는 textField 라면, mode 에 대한 enum 을 선언하는것이 더 명확해보입니다!
1. SignUpTextField 의 mode 변수를 선언해놓고 get/set 이나 willSet/didSet 구문을 이용해 변수값만 변경하면 알아서 뷰가 세팅되도록 구현해볼수도 있을것 같습니다~!
2. 혹은 toAlertMode/toBasicMode 함수를 하나로 합치고 변수로 모드타입을 받아 적용하는 방법도 있을 수 있습니다~

2022-01-20 09:45 UTC, lauren-c-kakaoent commented on KakaoProfile/KakaoProfile/SignUpViewController.swift
> +        if !User.isValidPassword(password: password, patterns: [.LENGTH]) {
d67353b81d0afa052d5108ebe272ade5dcc0807c 
확인 감사합니다 큐! 가능한 문자에 대한 안내도 포함해서 안내문구 수정하였습니다!

2022-01-21 01:16 UTC, lauren-c-kakaoent commented on KakaoProfile/KakaoProfile/signup/SignUpViewController.swift
> +    @IBAction func idInputDidEnd(_ sender: SignUpTextField) {
4b004599c79bfcc2893ddf1ffaf6e6e4e70a1397 EditingDidEnd에 대해서 text edit에 공통적으로 `validateContent()` 함수를 추가하여 하나로 통합해봤습니다! changed도 계속 고민해보겟습니다. 감사합니다!

2022-01-21 01:17 UTC, lauren-c-kakaoent commented on KakaoProfile/KakaoProfile/signup/SignUpTextField.swift
> +    }
29628e26a73cae07b61f6842d98b6f68ccfa749b `mode` 변수를 다른 곳에서 사용할 일이 없을거라고 생각해서 말씀해주신 방법 중 두번째 방법을 이용해서 변경해봤습니다. 감사합니다!!

2022-01-21 02:06 UTC, bamiboo approved these changes

2022-01-21 02:11 UTC, kyoo-sl approved these changes
확인했습니다~

2022-01-21 02:56 UTC, merged